version: "3.8"

services:
  database:
    image: postgres:15-alpine
    container_name: applydash_db
    environment:
      POSTGRES_DB: applydash_db
      POSTGRES_USER: ${DB_USER} # Use environment variables for secrets
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    restart: unless-stopped

  backend:
    build:
      context: ./backend # Path to your backend's Dockerfile
    container_name: applydash_backend
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/applydash_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - APPLYDASH_API_SECRET_KEY=${API_SECRET_KEY} # Pass the secret key
      - CORS_ALLOWED_ORIGINS=http://your_vps_ip_or_domain # Set the production origin
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend # Path to your frontend's Dockerfile
    container_name: applydash_frontend
    ports:
      - "80:80" # Map port 80 of your VPS to port 80 of the container
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
