version: "3.8"

services:
  database:
    image: postgres:15-alpine
    container_name: applydash_db
    environment:
      POSTGRES_DB: applydash_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: applydash_backend
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/applydash_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - APPLYDASH_API_SECRET_KEY=${API_SECRET_KEY}
      - CORS_ALLOWED_ORIGINS=https://applydash.haguma.com
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: applydash_frontend
    # NO PORTS EXPOSED HERE (Caddy will handle external traffic)
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - default # Keep it on its default network to talk to the backend/db
      - caddy_network # Also connect it to the shared Caddy network
    # --------------------------

volumes:
  postgres_data:
  
# ---- AND ADD THIS AT THE BOTTOM ----
networks:
  caddy_network:
    external: true
# ------------------------------------